Toolbar and headline for mobile version
Piercel2022/mobile-version-skeleton pull request #1
Opened 2022-04-20 12:34 UTC by Piercel2022

Mobile skeleton with toolbar and headline in figma design coding in html and css

2022-04-20 20:45 UTC, nicupop729 requested changes
# STATUS: Required Changes ♻️

Hi @Piercel2022, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


<img src="https://media3.giphy.com/media/5hgYDDh5oqbmE4OKJ3/giphy.gif"/>

### Some highlights for you
* Correct GitHub flow practice ✔️ 
* Good commit messages ✔️ 
* Professional README ✔️ 

### Required Changes ♻️

- [ ] Kindly, build the README file in order to have a fully professional repo, but please, without skipping sections from it;
Here is the [README template](https://github.com/microverseinc/readme-template)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 20:45 UTC, nicupop729 commented on index.html
> +
- [ ] Kindly, remove empty lines from your file as they are redundant and make your file look messy and unprofessional;

2022-04-20 20:45 UTC, nicupop729 commented on index.html
> +            </section>
In order to respect the good practices and in order for us to make use of semantic HTML tags, kindly replace this `section` tag with `header`, being is more appropriate for this part of the project;

2022-04-20 20:45 UTC, nicupop729 commented on index.html
> +            <h1>My Logo</h1>
We should only make use of the `h1` tag once in our project. This is not the case for the logo, should not be beheld by an `h1` tag.

- [ ] Kindly, replace the tag with something more appropriate;

2022-04-20 20:45 UTC, nicupop729 commented on styles.css
> +}
As the project requirements specifically ask for, the toolbar needs to be aligned with flexbox;

I noticed that you gave the `justify-content` but in order to do that, first you have to display it as flex;

- [ ] Please, make use of flexbox to align this toolbar;

2022-04-20 20:45 UTC, nicupop729 commented on styles.css
> +  position: absolute;
As the project requirements specifically ask for, the toolbar needs to be aligned with flexbox; 

- [ ] Keeping this in mind, kindly, display the logo making use of flexbox and not of absolute positioning; Please remove the absolute positioning;

2022-04-20 20:45 UTC, nicupop729 commented on styles.css
> +  flex-direction: column;
As an advice, before setting the flex-direction, we need to specifically display it as  flex in order for the flex-direction to work as intended;

2022-04-20 20:45 UTC, nicupop729 commented on index.html
> +            </div>
Because these images are representing just the background and they don't have a meaning apart from that in the project, they don't belong to the HTML file;

- [ ] Kindly, remove the images from the HTML file and introduce them to the project thru out the CSS file as background images; :+1:

2022-04-20 20:45 UTC, nicupop729 commented on styles.css
> +
- [ ]  In order to remove the white spaces from the margins of your project, it is recommended and advisable to start the CSS styling from the first line of code with the following:

`* {
  margin: 0; 
  padding: 0;
  box-sizing:border-box;
}`

The '*' means that these settings will apply to the whole of the project. From that point on we can over write other styling properties only to the elements that concern us;

2022-04-20 20:45 UTC, nicupop729 commented on styles.css
> +
At the moment, your design looks like this:
![image](https://user-images.githubusercontent.com/83596135/164319051-3c42bbeb-a66a-4c2f-837a-9ecd04efb518.png)

2 main problems:

- [ ] Text is overlapping; 
- [ ] Unwanted margins on the left and top part;

If you apply the above mention settings, you will have it like this:
![image](https://user-images.githubusercontent.com/83596135/164319402-d357b169-6a81-4463-ad7f-5b888f90b4d9.png)

- [ ] Apply your desired setting, but, kindly, remove the top and left unwanted margins and undo the overlapping text;

2022-04-21 06:07 UTC, Piercel2022 commented on index.html
> +            </section>
@nicupop729 OK

2022-04-21 06:12 UTC, Piercel2022 commented on index.html
> +            <h1>My Logo</h1>
@nicupop729 OK

2022-04-21 06:38 UTC, Piercel2022 commented on index.html
> +            </div>
@nicupop729 I used CSS classes to position these images in html, is possible to place these images in CSS without classes? In that case, I need only to know the position, right?

2022-04-21 06:46 UTC, Piercel2022 commented on styles.css
> +
@nicupop729 OK thanks

2022-04-21 07:06 UTC, Piercel2022 commented on styles.css
> +  position: absolute;
@nicupop729 OK

2022-04-21 07:23 UTC, Piercel2022 commented on styles.css
> +}
Good

2022-04-22 00:27 UTC, roshan-bajgain approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏
## Optional 

- [ ] Your project is not responsible So kindly work on it and it will be easier for you In future when you have to work for next milestone

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-04-22 05:27 UTC, merged